export const GESTION_TIPO_CONTRATO = 'GESTION_TIPO_CONTRATO';
export const GESTION_ROLES = 'GESTION_ROLES';
export const GESTION_ROL_PERMISOS = 'GESTION_ROL_PERMISOS';
export const GESTION_USUARIO = 'GESTION_USUARIO';
export const GESTION_PROCESOS = 'GESTION_PROCESOS';
export const GESTION_TIPO_DOCUMENTOS = 'GESTION_TIPO_DOCUMENTOS';
export const GESTION_MEDIO_PAGO = 'GESTION_MEDIO_PAGO';
export const GESTION_TIPO_PAGO = 'GESTION_TIPO_PAGO';
export const GESTION_TIPO_TRANSACCION = 'GESTION_TIPO_TRANSACCION';
<<<<<<< HEAD
export const GESTION_COMPETENCIA = 'GESTION_COMPETENCIA';
export const GESTION_JORNADA = 'GESTION_JORNADA';
=======
export const GESTION_GRUPO = 'GESTION_GRUPO';
export const GESTION_TIPO_GRUPO = 'GESTION_TIPO_GRUPO';
>>>>>>> a509124f95f42e0765974f4d23ef976021522d54

